package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"atd-tools/pkg/atom"
	"atd-tools/pkg/ollama"
	"atd-tools/pkg/pipeline"
	"atd-tools/pkg/prompt"
	"github.com/spf13/cobra"
)

var compareCmd = &cobra.Command{
	Use:   "compare",
	Short: "Compare two atoms for semantic overlap",
	Long: `Compare performs a deep pairwise analysis of two ATD atoms.

It identifies shared keywords, diagnoses their relationship, and proposes
a resolution to maintain architectural integrity.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		aPath, _ := cmd.Flags().GetString("a")
		bPath, _ := cmd.Flags().GetString("b")
		outPath, _ := cmd.Flags().GetString("out")

		if aPath == "" || bPath == "" {
			return fmt.Errorf("both -a and -b atom paths are required")
		}

		return runCompare(aPath, bPath, outPath)
	},
}

func sharedKeywords(a, b string) []string {
	freq := make(map[string]int)
	stopwords := map[string]bool{
		"the": true, "a": true, "an": true, "to": true, "of": true, "and": true,
		"is": true, "in": true, "for": true, "that": true, "this": true,
		"it": true, "be": true, "are": true, "at": true, "by": true,
	}
	tokenize := func(s string) []string {
		s = strings.ToLower(s)
		var out []string
		for _, w := range strings.Fields(s) {
			w = strings.Trim(w, ".,;:\"'()[]{}*-")
			if len(w) > 3 && !stopwords[w] {
				out = append(out, w)
			}
		}
		return out
	}
	for _, w := range tokenize(a) {
		freq[w]++
	}
	var shared []string
	seen := make(map[string]bool)
	for _, w := range tokenize(b) {
		if freq[w] > 0 && !seen[w] {
			shared = append(shared, w)
			seen[w] = true
		}
	}
	if len(shared) > 10 {
		shared = shared[:10]
	}
	return shared
}

func runCompare(aPath, bPath, outPath string) error {
	atomA, err := atom.Parse(aPath)
	if err != nil {
		return fmt.Errorf("failed to parse atom A: %v", err)
	}
	atomB, err := atom.Parse(bPath)
	if err != nil {
		return fmt.Errorf("failed to parse atom B: %v", err)
	}

	// Prepare data for prompt (using prompt-specific AtomData struct)
	pdA := prompt.AtomData{HumanName: atomA.HumanName, Type: atomA.Type, Intent: atomA.Intent, Logic: atomA.Logic}
	pdB := prompt.AtomData{HumanName: atomB.HumanName, Type: atomB.Type, Intent: atomB.Intent, Logic: atomB.Logic}
	requestPrompt := prompt.CompareBuild(pdA, pdB)

	var resolution string
	resp, err := ollama.Query("compare", requestPrompt, prompt.CompareFormat())
	if err == ollama.ErrIDEFallback {
		promptName := fmt.Sprintf("compare_%s_%s", atomA.ID, atomB.ID)
		pipeline.WritePromptFile(promptName, requestPrompt)
		resolution = "_(Resolution pending in task_list — IDE Fallback)_"
	} else if err != nil {
		resolution = fmt.Sprintf("_(LLM error: %v)_", err)
	} else {
		resolution = resp.Response
	}

	keywords := sharedKeywords(atomA.Intent+" "+atomA.Logic, atomB.Intent+" "+atomB.Logic)
	kwStr := strings.Join(keywords, ", ")
	if kwStr == "" { kwStr = "_none detected_" }

	out := "# ATD Collision Report\n\n"
	out += "> **Generated by:** atd compare  \n"
	out += "> **Status:** ⚠️ SEMANTIC OVERLAP DETECTED\n\n---\n\n"

	for _, d := range []struct{Label string; Data atom.AtomData; Path string}{{"A", atomA, aPath}, {"B", atomB, bPath}} {
		out += fmt.Sprintf("## Atom %s — %s\n\n", d.Label, d.Data.HumanName)
		out += "| Field | Value |\n|-------|-------|\n"
		out += fmt.Sprintf("| **ID** | `%s` |\n", d.Data.ID)
		out += fmt.Sprintf("| **Type** | %s |\n", d.Data.Type)
		out += fmt.Sprintf("| **File** | `%s` |\n\n", filepath.Base(d.Path))
		out += "### Intent\n> " + d.Data.Intent + "\n\n"
		out += "### Rule / Logic\n```\n" + d.Data.Logic + "\n```\n\n---\n\n"
	}

	out += "## Overlap Analysis\n\n"
	out += "| Shared Keywords |\n|----------------|\n"
	out += "| " + kwStr + " |\n\n"
	out += "## Proposed Resolution\n\n" + resolution + "\n"

	if outPath == "" {
		fmt.Println(out)
	} else {
		err := os.WriteFile(outPath, []byte(out), 0644)
		if err != nil {
			return fmt.Errorf("failed to write report: %v", err)
		}
		fmt.Printf("Report written to: %s\n", outPath)
	}

	return nil
}

func init() {
	rootCmd.AddCommand(compareCmd)
	compareCmd.Flags().StringP("a", "a", "", "Path to first atom")
	compareCmd.Flags().StringP("b", "b", "", "Path to second atom")
	compareCmd.Flags().String("out", "", "Report output path")
}
