package cmd
// @spec-link [[atd_continue]]

import (
	"fmt"
	"os"
	"atd-tools/pkg/pipeline"
	"github.com/spf13/cobra"
)

var continueCmd = &cobra.Command{
	Use:   "continue [task_list.md]",
	Short: "Resume execution from a task list after IDE Agent completes work",
	Long: `Reads a task_list.md generated by a previous atd command,
checks which .result files have been created by the IDE Agent,
marks completed tasks, and reports remaining work.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		tl, err := pipeline.ParseTaskList(args[0])
		if err != nil {
			return err
		}

		completedCount := 0
		// Check which result files now exist
		for i, entry := range tl.Entries {
			if entry.Done {
				continue
			}
			if entry.File != "" {
				if _, err := os.Stat(entry.File); err == nil {
					if err := tl.MarkDone(i); err != nil {
						return fmt.Errorf("failed to mark task %d as done: %v", i, err)
					}
					fmt.Printf("[✓] Completed: %s\n", entry.Text)
					completedCount++
				}
			}
		}

		if completedCount == 0 {
			fmt.Println("No new completed tasks detected.")
		}

		next := tl.NextPending()
		if next == -1 {
			fmt.Println("All tasks complete.")
			return nil
		}

		fmt.Printf("\nNext pending task:\n  %s\n", tl.Entries[next].Text)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(continueCmd)
}
