package pipeline

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

// TaskEntry represents one line in the task list.
type TaskEntry struct {
	Done bool
	Text string
	File string // Extracted result file path from the task text
}

// TaskList represents a parsed task_list.md.
type TaskList struct {
	GeneratedBy string
	Entries     []TaskEntry
	FilePath    string
}

// ParseTaskList reads a task_list.md and returns structured entries.
func ParseTaskList(path string) (*TaskList, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	tl := &TaskList{FilePath: path}
	scanner := bufio.NewScanner(file)
	
	// Regex for extraction: `path/to/file.result`
	resultRegex := regexp.MustCompile("`([^`]+\\.result)`")

	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "Generated by: ") {
			tl.GeneratedBy = strings.TrimPrefix(line, "Generated by: ")
			continue
		}

		// Match checkbox lines: * [ ] or * [x]
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "* [") {
			entry := TaskEntry{}
			if strings.HasPrefix(trimmed, "* [x]") {
				entry.Done = true
			}
			
			// Extract text after [ ] or [x]
			text := strings.TrimSpace(trimmed[5:])
			entry.Text = text
			
			// Try to find result file in backticks
			matches := resultRegex.FindStringSubmatch(text)
			if len(matches) > 1 {
				entry.File = matches[1]
			}
			
			tl.Entries = append(tl.Entries, entry)
		}
	}

	return tl, scanner.Err()
}

// MarkDone marks a task as completed in the task list file.
func (tl *TaskList) MarkDone(index int) error {
	if index < 0 || index >= len(tl.Entries) {
		return fmt.Errorf("invalid task index: %d", index)
	}

	content, err := os.ReadFile(tl.FilePath)
	if err != nil {
		return err
	}

	lines := strings.Split(string(content), "\n")
	taskCount := 0
	
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "* [") {
			if taskCount == index {
				// Replace [ ] with [x]
				prefixEnd := strings.Index(line, "[")
				if prefixEnd != -1 && len(line) > prefixEnd+2 {
					lines[i] = line[:prefixEnd+1] + "x" + line[prefixEnd+2:]
				}
				tl.Entries[index].Done = true
				break
			}
			taskCount++
		}
	}

	return os.WriteFile(tl.FilePath, []byte(strings.Join(lines, "\n")), 0644)
}

// NextPending returns the index of the next incomplete task, or -1.
func (tl *TaskList) NextPending() int {
	for i, entry := range tl.Entries {
		if !entry.Done {
			return i
		}
	}
	return -1
}
