package pipeline

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
	"atd-tools/config"
)

// PendingTask describes one unit of work for the IDE Agent.
type PendingTask struct {
	PromptFile   string // Path to the .prompt file to read
	ResultFile   string // Path where IDE Agent should write the result
	Instruction  string // Human-readable instruction
	OutputSchema string // Expected JSON schema description
}

// WritePromptFile writes an LLM prompt to pipeline_output/<name>.prompt
func WritePromptFile(name, prompt string) (string, error) {
	dir := filepath.Join(config.ProjectRoot(), "pipeline_output")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, name+".prompt")
	return path, os.WriteFile(path, []byte(prompt), 0644)
}

// WriteTaskList writes a task_list.md for IDE Agent with pending tasks.
func WriteTaskList(toolName string, tasks []PendingTask) (string, error) {
	dir := filepath.Join(config.ProjectRoot(), "pipeline_output")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "task_list.md")

	var sb strings.Builder
	sb.WriteString("# ATD Task List\n")
	sb.WriteString(fmt.Sprintf("Generated by: atd %s\n", toolName))
	sb.WriteString(fmt.Sprintf("Generated at: %s\n\n", time.Now().Format(time.RFC3339)))

	sb.WriteString("## Pending Tasks\n")
	for _, t := range tasks {
		sb.WriteString(fmt.Sprintf("* [ ] Read `%s`, %s, output JSON to `%s`\n", t.PromptFile, t.Instruction, t.ResultFile))
	}
	sb.WriteString(fmt.Sprintf("* [ ] Then run: `atd continue %s`\n\n", path))

	sb.WriteString("## Output Format\n")
	sb.WriteString("Write your response as a JSON file to the `.result` path. Schema:\n")
	for _, t := range tasks {
		if t.OutputSchema != "" {
			sb.WriteString(fmt.Sprintf("- For `%s`: %s\n", t.ResultFile, t.OutputSchema))
		}
	}

	sb.WriteString("\n## Context\n")
	sb.WriteString(fmt.Sprintf("- Project root: %s\n", config.ProjectRoot()))

	return path, os.WriteFile(path, []byte(sb.String()), 0644)
}
