package pipeline

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseTaskList(t *testing.T) {
	content := `# ATD Task List
Generated by: atd map

## Pending Tasks
* [ ] Read ` + "`" + `file1.prompt` + "`" + `, do X, output to ` + "`" + `file1.result` + "`" + `
* [x] Completed task ` + "`" + `file2.result` + "`" + `
`
	tmpFile := filepath.Join(t.TempDir(), "task_list.md")
	if err := os.WriteFile(tmpFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	tl, err := ParseTaskList(tmpFile)
	if err != nil {
		t.Fatalf("ParseTaskList failed: %v", err)
	}

	if tl.GeneratedBy != "atd map" {
		t.Errorf("Expected GeneratedBy=atd map, got %s", tl.GeneratedBy)
	}

	if len(tl.Entries) != 2 {
		t.Fatalf("Expected 2 entries, got %d", len(tl.Entries) )
	}

	if tl.Entries[0].Done {
		t.Error("Task 0 should not be done")
	}
	if tl.Entries[0].File != "file1.result" {
		t.Errorf("Expected file1.result, got %s", tl.Entries[0].File)
	}

	if !tl.Entries[1].Done {
		t.Error("Task 1 should be done")
	}
}

func TestMarkDone(t *testing.T) {
	content := `## Pending Tasks
* [ ] First
* [ ] Second
`
	tmpFile := filepath.Join(t.TempDir(), "task_list.md")
	if err := os.WriteFile(tmpFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	tl, err := ParseTaskList(tmpFile)
	if err != nil {
		t.Fatal(err)
	}

	if err := tl.MarkDone(0); err != nil {
		t.Fatalf("MarkDone failed: %v", err)
	}

	updated, _ := os.ReadFile(tmpFile)
	if !strings.Contains(string(updated), "* [x] First") {
		t.Errorf("File not updated correctly:\n%s", string(updated))
	}

	if tl.NextPending() != 1 {
		t.Errorf("Expected next pending 1, got %d", tl.NextPending())
	}
}

func TestWriteTaskList(t *testing.T) {
	// This requires config.ProjectRoot() to work.
	// We'll mock it if necessary but let's see if we can just test the formatting.
	tasks := []PendingTask{
		{PromptFile: "p1", ResultFile: "r1", Instruction: "do it", OutputSchema: "schema1"},
	}
	
	path, err := WriteTaskList("test-tool", tasks)
	if err != nil {
		t.Fatalf("WriteTaskList failed: %v", err)
	}
	defer os.RemoveAll(filepath.Dir(path))

	content, _ := os.ReadFile(path)
	s := string(content)
	if !strings.Contains(s, "Generated by: atd test-tool") {
		t.Error("Missing header")
	}
	if !strings.Contains(s, "* [ ] Read `p1`") {
		t.Error("Missing task line")
	}
	if !strings.Contains(s, "schema1") {
		t.Error("Missing schema")
	}
}
